{
 "title": "Project",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster or Node CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "ProjectName",
    "label": "ProjectName",
    "query": "label_values(kube_namespace_labels, label_monitoring_pandaria_io_projectName)"
   },
   {
    "name": "ProjectID",
    "label": "ProjectID",
    "query": "label_values(kube_namespace_labels{label_monitoring_pandaria_io_projectName=~\"$ProjectName\"}, label_field_cattle_io_projectId)"
   },
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": "label_values(kube_namespace_labels{label_field_cattle_io_projectId=~\"$ProjectID\"},namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Counts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Namespaces Counts",
     "type": "stat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(kube_namespace_labels{label_field_cattle_io_projectId=~\"$ProjectID\"})",
       "legendFormat": "Counts"
      }
     ]
    },
    {
     "title": "Deployment Counts",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(kube_deployment_metadata_generation{namespace=~\"$Namespace\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "DaemonSet Counts",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(kube_daemonset_metadata_generation{namespace=~\"$Namespace\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "StatefulSet Counts",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(kube_statefulset_metadata_generation{namespace=~\"$Namespace\"}) or vector(0)"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU and Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods CPU usage TOP5",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "topk(5,sum  by (pod_name) (rate (container_cpu_usage_seconds_total{pod_name!=\"\",container_name!=\"POD\",namespace=~\"$Namespace\"}[5m])))",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Pods Memory usage TOP5",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "topk(5,sum by (pod_name) (container_memory_working_set_bytes{pod_name!=\"\",namespace=~\"$Namespace\"}))",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Pods CPU usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "percentunit", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{pod_name!=\"\",container_name!=\"POD\",namespace=~\"$Namespace\"}[5m])) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Pods Memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{pod_name!=\"\",namespace=~\"$Namespace\"}) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Project CPU Quota",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(kube_resourcequota{resource=\"limits.cpu\",type=~\"hard\"})",
       "legendFormat": "{{namespace}}-hard"
      },
      {
       "expr": "sum(kube_resourcequota{resource=\"limits.cpu\",type=~\"used\"})",
       "legendFormat": "{{namespace}}-used"
      }
     ]
    },
    {
     "title": "CPU Quota",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
     "repeat": "Namespace",
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(kube_resourcequota{resource=\"limits.cpu\",namespace=~\"$Namespace\",type=~\"hard\"}) by (namespace)",
       "legendFormat": "{{namespace}}-hard"
      },
      {
       "expr": "sum(kube_resourcequota{resource=\"limits.cpu\",namespace=~\"$Namespace\",type=~\"used\"}) by (namespace)",
       "legendFormat": "{{namespace}}-used"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Project Memory Quota",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(kube_resourcequota{resource=\"limits.memory\",type=~\"hard\"}) ",
       "legendFormat": "hard"
      },
      {
       "expr": "sum(kube_resourcequota{resource=\"limits.memory\",type=~\"used\"})",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Memory Quota",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
     "repeat": "Namespace",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(kube_resourcequota{resource=\"limits.memory\",namespace=~\"$Namespace\",type=~\"hard\"}) by (namespace)",
       "legendFormat": "{{namespace}}-hard"
      },
      {
       "expr": "sum(kube_resourcequota{resource=\"limits.memory\",namespace=~\"$Namespace\",type=~\"used\"}) by (namespace)",
       "legendFormat": "{{namespace}}-used"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods Running",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$Namespace\",phase=\"Running\"})"
      }
     ]
    },
    {
     "title": "Pods Pending",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$Namespace\",phase=\"Pending\"})"
      }
     ]
    },
    {
     "title": "Pods Failed",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$Namespace\",phase=\"Failed\"})"
      }
     ]
    },
    {
     "title": "Pods Succeeded",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$Namespace\",phase=\"Succeeded\"})"
      }
     ]
    },
    {
     "title": "Pods Unknown",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$Namespace\",phase=\"Unknown\"})"
      }
     ]
    },
    {
     "title": "Running Pods",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$Namespace\",phase=\"Running\"} == 1) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pending Pods",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$Namespace\",phase=\"Pending\"} == 1) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Failed Pods",
     "type": "table",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$Namespace\",phase=\"Failed\"} == 1) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Succeeded Pods",
     "type": "table",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 19 },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$Namespace\",phase=\"Succeeded\"} == 1) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Unknown Pods",
     "type": "table",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 19 },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$Namespace\",phase=\"Unknown\"} == 1) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Deployment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Deployment",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "sum(kube_deployment_spec_replicas{namespace=~\"$Namespace\"}) by (deployment)",
       "legendFormat": "{{deployment}}"
      },
      {
       "expr": "sum(kube_deployment_status_replicas{namespace=~\"$Namespace\"}) by (deployment)",
       "legendFormat": "{{deployment}}"
      },
      {
       "expr": "sum(kube_deployment_status_replicas_available{namespace=~\"$Namespace\"}) by (deployment)",
       "legendFormat": "{{deployment}}"
      },
      {
       "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$Namespace\"}) by (deployment)",
       "legendFormat": "{{deployment}}"
      },
      {
       "expr": "sum(kube_deployment_status_replicas_updated{namespace=~\"$Namespace\"}) by (deployment)",
       "legendFormat": "{{deployment}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DaemonSet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "DaemonSet",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "sum(kube_daemonset_status_number_ready{namespace=~\"$Namespace\"}) by (daemonset)",
       "legendFormat": "{{daemonset}}"
      },
      {
       "expr": "sum(kube_daemonset_status_number_available{namespace=~\"$Namespace\"}) by (daemonset)",
       "legendFormat": "{{daemonset}}"
      },
      {
       "expr": "sum(kube_daemonset_status_number_unavailable{namespace=~\"$Namespace\"}) by (daemonset)",
       "legendFormat": "{{daemonset}}"
      },
      {
       "expr": "sum(kube_daemonset_status_number_misscheduled{namespace=~\"$Namespace\"}) by (daemonset)",
       "legendFormat": "{{daemonset}}"
      }
     ]
    }
   ]
  },
  {
   "title": "StatefulSet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "StatefulSet",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum(kube_statefulset_replicas{namespace=~\"$Namespace\"}) by (statefulset)",
       "legendFormat": "{{statefulset}}"
      },
      {
       "expr": "sum(kube_statefulset_status_replicas{namespace=~\"$Namespace\"}) by (statefulset)",
       "legendFormat": "{{statefulset}}"
      }
     ]
    }
   ]
  }
 ]
}