{{- if .Values.exporter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: exporter-{{ .Release.Name }}
  labels:
    app: {{ template "app.fullname" . }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: exporter
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: {{ template "app.fullname" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    component: exporter
  ports:
    - name: http
      port: 80
      targetPort: 80
{{- end }}