apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: {{ template "app.fullname" . }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: query
  name: thanos-query-{{ template "app.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "app.fullname" . }}
      chart: {{ .Chart.Name }}
      release: {{ .Release.Name }}
      component: query
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace | quote }}
  endpoints:
  - port: http
    relabelings:
    - sourceLabels:
      - __meta_kubernetes_pod_host_ip
      targetLabel: host_ip
      action: replace
      regex: (.+)
      replacement: $1
    - sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: node
      action: replace
      regex: (.+)
      replacement: $1
