{{- if .Values.thanos.rule.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: thanos-rule-{{ .Release.Name }}
  labels:
    app: {{ template "app.fullname" . }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
stringData:
  thanos.rule.yaml: |-
{{ toYaml .Values.thanos.rule.config | indent 6 }}
{{- end }}