apiVersion: v1
kind: ServiceAccount
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
{{- range .Values.global.imagePullSecrets }}
  - name: {{ . }}
{{- end }}
{{- end }}
metadata:
  name: istio-reader-service-account
  namespace: {{ .Values.global.istioNamespace }}
  labels:
    app: istio-reader
    chart: {{ template "base.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: ServiceAccount
  {{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- range .Values.global.imagePullSecrets }}
  - name: {{ . }}
  {{- end }}
  {{- end }}
metadata:
  name: istiod-service-account
  namespace: {{ .Values.global.istioNamespace }}
  labels:
    app: istiod
    chart: {{ template "base.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
---
