{
 "title": "Volumes",
 "description": "Dashboard of volume information.",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "volume_namespace",
    "label": "Namespace",
    "query": "label_values(kube_persistentvolumeclaim_info, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "PV", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pending",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase{phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Available",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase{phase=\"Available\"})"
    }
   ]
  },
  {
   "title": "Bound",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase{phase=\"Bound\"})"
    }
   ]
  },
  {
   "title": "Released",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase{phase=\"Released\"})"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase{phase=\"Failed\"})"
    }
   ]
  },
  { "title": "PVC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Pending",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{phase=\"Pending\", namespace=\"$volume_namespace\"})"
    }
   ]
  },
  {
   "title": "Bound",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{phase=\"Bound\", namespace=\"$volume_namespace\"})"
    }
   ]
  },
  {
   "title": "Lost",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{phase=\"Lost\", namespace=\"$volume_namespace\"})"
    }
   ]
  },
  {
   "title": "Running PVC Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(kubelet_volume_stats_used_bytes{exported_namespace=\"$volume_namespace\"}) by (persistentvolumeclaim, exported_namespace) ) / (sum(kubelet_volume_stats_capacity_bytes{exported_namespace=\"$volume_namespace\"}) by (persistentvolumeclaim, exported_namespace) ) * 100",
     "legendFormat": "{{exported_namespace}} ({{persistentvolumeclaim}})"
    }
   ]
  },
  {
   "title": "PVC Stats",
   "type": "table-old",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "kube_persistentvolumeclaim_info{namespace=\"$volume_namespace\"}"
    },
    {
     "expr": " 1 - count(kube_persistentvolumeclaim_info{namespace=\"$volume_namespace\"}) by (persistentvolumeclaim) + count(kubelet_volume_stats_used_bytes{exported_namespace=\"$volume_namespace\"}) by (persistentvolumeclaim)"
    },
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{exported_namespace=\"$volume_namespace\"}) by (persistentvolumeclaim,exported_namespace)"
    },
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes{exported_namespace=\"$volume_namespace\"}) by (persistentvolumeclaim,exported_namespace)"
    },
    {
     "expr": "sum(kubelet_volume_stats_available_bytes{exported_namespace=\"$volume_namespace\"}) by (persistentvolumeclaim,exported_namespace)"
    },
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{exported_namespace=\"$volume_namespace\"}) by (persistentvolumeclaim,exported_namespace) / sum(kubelet_volume_stats_capacity_bytes{exported_namespace=\"$volume_namespace\"}) by (persistentvolumeclaim,exported_namespace)"
    }
   ]
  }
 ]
}