apiVersion: {{ template "operator_api_version" . }}
kind: Alertmanager
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
{{- if .Values.securityContext }}
  securityContext:
{{ toYaml .Values.securityContext | indent 4 }}
{{- end }}
  podMetadata:
    labels:
      app: {{ template "app.name" . }}
      chart: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  baseImage: {{ template "system_default_registry" . }}{{ .Values.image.repository }}
  nodeSelector:
{{- include "linux-node-selector" . | nindent 4 }}
{{- with .Values.nodeSelector }}
  {{- toYaml . | nindent 4 }}
{{- end }}
  paused: {{ .Values.paused }}
  replicas: {{ .Values.replicaCount }}
  logLevel:  {{ .Values.logLevel }}
{{- if .Values.resources }}
  resources:
{{ toYaml .Values.resources | indent 4 }}
{{- end }}
  retention: "{{ .Values.retention }}"
{{- if .Values.secrets }}
  secrets:
{{ toYaml .Values.secrets | indent 4 }}
{{- end }}
{{- if or .Values.storageSpec .Values.persistence.enabled }}
  storage:
    volumeClaimTemplate:
      {{- if .Values.persistence.name }}
      metadata:
        name: {{ .Values.persistence.name }}
      {{- end }}
      spec:
{{- if .Values.storageSpec }}
{{ toYaml .Values.storageSpec | indent 8 }}
{{- else }}
        {{ if and .Values.persistence.storageClass (ne "default" .Values.persistence.storageClass) }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{ end }}
        accessModes: 
          - {{ default "ReadWriteOnce" .Values.persistence.accessMode }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
{{- end }}
{{- end }}
  version: "{{ .Values.image.tag }}"
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              app: {{ template "app.name" . }}
              alertmanager: {{ .Release.Name }}
  tolerations:
{{- include "linux-node-tolerations" . | nindent 4 }}
{{- if .Values.tolerations }}
{{ toYaml .Values.tolerations | indent 4 }}
{{- end }}
