apiVersion: v1
kind: Service
metadata:
  name: expose-alertmanager-metrics
  labels:
    app: {{ template "app.name" . }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    {{ .Values.apiGroup }}: "true"
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: {{ template "app.name" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  ports:
    - name: http
      port: 9093
      targetPort: web