apiVersion: v1
kind: Service
metadata:
  name: access-alertmanager
  labels:
    app: {{ template "app.name" . }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    kubernetes.io/cluster-service: "true"
spec:
  type: ClusterIP
  selector:
    app: {{ template "app.name" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  ports:
    - name: http
      port: 80
      targetPort: web
