apiVersion: v1
kind: ServiceAccount
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
{{- range .Values.global.imagePullSecrets }}
  - name: {{ . }}
{{- end }}
{{- end }}
metadata:
  name: {{ .Values.name | default "istio-ingressgateway" }}-service-account
  namespace: {{ .Release.Namespace }}
  labels:
{{ .Values.labels | toYaml | trim | indent 4 }}
    istio.io/rev: {{ .Values.revision | default "default" }}
    install.operator.istio.io/owning-resource: {{ .Values.ownerName | default "unknown" }}
    operator.istio.io/component: "IngressGateways"
    chart: {{ template "istio-ingress.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
