apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name | default "istio-egressgateway" }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- range $key, $val := .Values.serviceAnnotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  labels:
{{ .Values.labels | toYaml | indent 4 }}
    istio.io/rev: {{ .Values.revision | default "default" }}
    install.operator.istio.io/owning-resource: {{ .Values.ownerName | default "unknown" }}
    operator.istio.io/component: "EgressGateways"
    chart: {{ template "istio-egress.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
{{ .Values.labels | toYaml | indent 4 }}
  ports:
    {{- range $key, $val := .Values.ports }}
    -
      {{- range $pkey, $pval := $val }}
      {{ $pkey }}: {{ $pval }}
      {{- end }}
    {{- end }}
---
