apiVersion: v1
kind: Secret
metadata:
  name: webhook-receiver
  labels:
    app: {{ template "app.name" . }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  config.yaml: {{ toYaml ( required "you must provide config for init" .Values.config ) | b64enc }} 