{
 "title": "Cluster Resource",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "label": "节点",
    "query": "label_values(kube_node_info,node)"
   },
   {
    "name": "ProjectName",
    "label": "项目",
    "query": "label_values(kube_namespace_labels, label_monitoring_pandaria_io_project_name)"
   },
   {
    "name": "Namespace",
    "label": "命名空间",
    "query": "label_values(kube_namespace_labels{label_monitoring_pandaria_io_project_name=~\"$ProjectName\"},namespace)"
   },
   {
    "name": "Container",
    "label": "容器应用",
    "query": "label_values(kube_pod_container_info{namespace=~\"$Namespace\"},container)"
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": "label_values(kube_pod_container_info{namespace=~\"$Namespace\",container=~\"$Container\"},pod)"
   }
  ]
 },
 "panels": [
  { "title": "Node resource overview ($Node)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "节点内存比例",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container_name!=\"POD\",container_name!=\"\",pod_name!=\"\",pod_name=~\"^$Pod$\",node=~\"^$Node$\"}) / sum (machine_memory_bytes{node=~\"^$Node$\"})",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\",pod=~\"^$Pod$\",node=~\"^$Node$\"}) / sum(kube_node_status_capacity{resource=\"memory\",node=~\"^$Node$\"})",
     "legendFormat": "内存请求率"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\",pod=~\"^$Pod$\",node=~\"^$Node$\"}) / sum(kube_node_status_capacity{resource=\"memory\",node=~\"^$Node$\"})",
     "legendFormat": "内存限制率"
    }
   ]
  },
  {
   "title": "节点CPU比例",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{container_name!=\"POD\",container_name!=\"\",pod_name!=\"\",pod_name=~\"^$Pod$\",node=~\"^$Node$\"}[5m])) / sum (machine_cpu_cores{node=~\"^$Node$\"})",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",pod=~\"^$Pod$\",node=~\"^$Node$\"}) / sum(kube_node_status_allocatable{resource=\"cpu\",node=~\"^$Node$\"})",
     "legendFormat": "CPU请求率"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\",pod=~\"^$Pod$\",node=~\"^$Node$\"}) / sum(kube_node_status_allocatable{resource=\"cpu\",node=~\"^$Node$\"})",
     "legendFormat": "CPU限制率"
    }
   ]
  },
  {
   "title": "节点与Pod",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_node_info{node=~\"^$Node$\"})",
     "legendFormat": "节点数"
    },
    {
     "expr": "count(kube_pod_info{created_by_kind!~\"<none>|Job\",node=~\"^$Node$\"})",
     "legendFormat": "Pod数"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"pods\",node=~\"^$Node$\"})",
     "legendFormat": "上限Pod"
    }
   ]
  },
  {
   "title": "命名空间资源明细",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "count(kube_pod_info{node=~\"^$Node$\"}) by (namespace)"
    },
    {
     "expr": "count(kube_service_info) by(namespace)"
    },
    {
     "expr": "count(count(kube_pod_container_info) by(container,namespace))by(namespace)"
    },
    {
     "expr": "count(kube_configmap_info) by(namespace)",
     "legendFormat": "configmap"
    },
    {
     "expr": "count(kube_secret_info) by(namespace)",
     "legendFormat": "secret"
    }
   ]
  },
  {
   "title": "网络流量总览（关联节点或命名空间）",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{node=~\"^$Node$\",namespace=~\"$Namespace\"}[2m]))*8",
     "legendFormat": "接收"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{node=~\"^$Node$\",namespace=~\"$Namespace\"}[2m]))*8",
     "legendFormat": "发送"
    }
   ]
  },
  {
   "title": "节点内存信息",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{node=~\"^$Node$\"})",
     "legendFormat": "总内存"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{container_name!=\"POD\",container_name!=\"\",pod_name!=\"\",pod_name=~\"^$Pod$\",node=~\"^$Node$\"})",
     "legendFormat": "使用量"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\",pod=~\"^$Pod$\",node=~\"^$Node$\"})",
     "legendFormat": "请求量"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\",pod=~\"^$Pod$\",node=~\"^$Node$\"})",
     "legendFormat": "限制量"
    }
   ]
  },
  {
   "title": "节点CPU核数",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{node=~\"^$Node$\"})",
     "legendFormat": "总核数"
    },
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{container_name!=\"POD\",container_name!=\"\",pod_name!=\"\",pod_name=~\"^$Pod$\",node=~\"^$Node$\"}[5m]))",
     "legendFormat": "使用量"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",pod=~\"^$Pod$\",node=~\"^$Node$\"})",
     "legendFormat": "请求量"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\",pod=~\"^$Pod$\",node=~\"^$Node$\"})",
     "legendFormat": "限制量"
    }
   ]
  },
  {
   "title": "节点存储信息",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{device=~\"^/dev/.*$\",node=~\"^$Node$\"}) - sum(node_filesystem_avail_bytes{device=~\"^/dev/.*$\",node=~\"^$Node$\"})) / sum (node_filesystem_size_bytes{device=~\"^/dev/.*$\",node=~\"^$Node$\"})",
     "legendFormat": "使用率"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{device=~\"^/dev/.*$\",node=~\"^$Node$\"}) - sum(node_filesystem_avail_bytes{device=~\"^/dev/.*$\",node=~\"^$Node$\"})",
     "legendFormat": "使用量"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{device=~\"^/dev/.*$\",node=~\"^$Node$\"})",
     "legendFormat": "总量"
    }
   ]
  },
  {
   "title": "节点信息（$Node）",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "kube_node_status_condition{status=\"true\",node=~\"^$Node$\"}",
     "legendFormat": "状态"
    },
    {
     "expr": "count(kube_pod_info{created_by_kind!~\"<none>|Job\",node=~\"^$Node$\"}) by (node)",
     "legendFormat": "Pod数"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"pods\",node=~\"^$Node$\"}) by (node)",
     "legendFormat": "Pod上限"
    },
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{container_name!=\"POD\",container_name!=\"\",pod_name!=\"\",pod_name=~\"^$Pod$\",node=~\"^$Node$\"}[5m])) by (node)",
     "legendFormat": "CPU使用"
    },
    {
     "expr": "kube_node_status_capacity{resource=\"cpu\",node=~\"^$Node$\"} - 0",
     "legendFormat": "总CPU"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",pod=~\"^$Pod$\",node=~\"^$Node$\"}) by (node)",
     "legendFormat": "CPU请求"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\",pod=~\"^$Pod$\",node=~\"^$Node$\"}) by (node)",
     "legendFormat": "CPU限制"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{container_name!=\"POD\",container_name!=\"\",pod_name!=\"\",pod_name=~\"^$Pod$\",node=~\"^$Node$\"}[5m])) by (node)) / (sum(machine_cpu_cores{node=~\"^$Node$\"}) by (node))",
     "legendFormat": "CPU使用%"
    },
    {
     "expr": "(sum(kube_pod_container_resource_requests{resource=\"cpu\",pod=~\"^$Pod$\",node=~\"^$Node$\"}) by (node)) / (sum(kube_node_status_allocatable{resource=\"cpu\",node=~\"^$Node$\"}) by (node))",
     "legendFormat": "CPU请求%"
    },
    {
     "expr": "(sum(kube_pod_container_resource_limits{resource=\"cpu\",pod=~\"^$Pod$\",node=~\"^$Node$\"}) by (node)) / (sum(kube_node_status_allocatable{resource=\"cpu\",node=~\"^$Node$\"}) by (node))",
     "legendFormat": "CPU限制"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{container_name!=\"POD\",container_name!=\"\",pod_name!=\"\",pod_name=~\"^$Pod$\",node=~\"^$Node$\"}) by (node)",
     "legendFormat": "内存使用"
    },
    {
     "expr": "kube_node_status_capacity{resource=\"memory\",node=~\"^$Node$\"} - 0",
     "legendFormat": "总内存"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\",node=~\"^$Node$\"}) by (node)",
     "legendFormat": "内存请求"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\",node=~\"^$Node$\"}) by (node)",
     "legendFormat": "内存限制"
    },
    {
     "expr": "(sum (container_memory_working_set_bytes{container_name!=\"POD\",container_name!=\"\",pod_name!=\"\",pod_name=~\"^$Pod$\",node=~\"^$Node$\"}) by (node)) / (sum (machine_memory_bytes{node=~\"^$Node$\"}) by (node))",
     "legendFormat": "内存使用%"
    },
    {
     "expr": "(sum(kube_pod_container_resource_requests{resource=\"memory\",pod=~\"^$Pod$\",node=~\"^$Node$\"}) by (node)) / (sum(kube_node_status_capacity{resource=\"memory\",node=~\"^$Node$\"}) by (node))",
     "legendFormat": "内存请求%"
    },
    {
     "expr": "(sum(kube_pod_container_resource_limits{resource=\"memory\",pod=~\"^$Pod$\",node=~\"^$Node$\"}) by (node)) / (sum(kube_node_status_capacity{resource=\"memory\",node=~\"^$Node$\"}) by (node))",
     "legendFormat": "内存限制%"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{device=~\"^/dev/.*$\",node=~\"^$Node$\"}) by (node) - sum(node_filesystem_avail_bytes{device=~\"^/dev/.*$\",node=~\"^$Node$\"}) by (node)",
     "legendFormat": "磁盘使用"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{device=~\"^/dev/.*$\",node=~\"^$Node$\"}) by (node)",
     "legendFormat": "总磁盘"
    },
    {
     "expr": "(sum(node_filesystem_size_bytes{device=~\"^/dev/.*$\",node=~\"^$Node$\"}) by (node) - sum(node_filesystem_avail_bytes{device=~\"^/dev/.*$\",node=~\"^$Node$\"}) by (node)) / (sum(node_filesystem_size_bytes{device=~\"^/dev/.*$\",node=~\"^$Node$\"})by (node))",
     "legendFormat": "磁盘使用%"
    }
   ]
  },
  {
   "title": "Container application resource overview（$Node）",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "容器应用资源统计（$Node）",
   "type": "table-old",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\",node=~\"^$Node$\"}[2m])) by (container)) / (sum(container_spec_cpu_quota{container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\",node=~\"^$Node$\"}/100000) by (container)) * 100"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\",node=~\"^$Node$\"}[2m])) by (container)",
     "legendFormat": "整体核数使用"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\",node=~\"^$Node$\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\",container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\",node=~\"^$Node$\"}) by (container)"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\",node=~\"^$Node$\"}) by (container)/ sum(container_spec_memory_limit_bytes{container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\",node=~\"^$Node$\"}) by (container) * 100"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\",node=~\"^$Node$\"}) by (container)"
    },
    {
     "expr": "sum (container_memory_rss{container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\",node=~\"^$Node$\"}) by (container)/ sum(container_spec_memory_limit_bytes{container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\",node=~\"^$Node$\"}) by (container) * 100",
     "legendFormat": "平均内存%(RSS)"
    },
    {
     "expr": "sum (container_memory_rss{container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\",node=~\"^$Node$\"}) by (container)",
     "legendFormat": "总内存使用(RSS) "
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\",container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\",node=~\"^$Node$\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\",container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\",node=~\"^$Node$\"}) by (container)"
    },
    {
     "expr": "sum(container_fs_usage_bytes{container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\",node=~\"^$Node$\"}) by (container)"
    },
    {
     "expr": "count(kube_pod_container_info{container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\",node=~\"^$Node$\"}) by(container) - 0"
    }
   ]
  },
  {
   "title": "Container application and Pod resource summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 }
  },
  {
   "title": "容器应用资源统计",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\"}[2m])) by (container) / (sum(container_spec_cpu_quota{container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\"}/100000) by (container)) * 100"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\"}[2m])) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\",container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\"}) by (container)"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\"}) by (container)/ sum(container_spec_memory_limit_bytes{container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\"}) by (container) * 100"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\"}) by (container)"
    },
    {
     "expr": "sum (container_memory_rss{container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\"}) by (container)/ sum(container_spec_memory_limit_bytes{container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\"}) by (container) * 100",
     "legendFormat": "平均内存%(RSS)"
    },
    {
     "expr": "sum (container_memory_rss{container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\"}) by (container)",
     "legendFormat": "总内存使用(RSS) "
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\",container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\",container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\"}) by (container)"
    },
    {
     "expr": "sum(container_fs_usage_bytes{container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\"}) by (container)"
    },
    {
     "expr": "count(kube_pod_container_info{container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\"}) by(container) - 0",
     "legendFormat": "容器数"
    }
   ]
  },
  {
   "title": "Pod资源明细",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{pod=~\"$Pod\",container=~\"$Container\",namespace=~\"$Namespace\"} == 1"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod=~\"$Pod\",container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\"}[2m])) by (container, pod) / (sum(container_spec_cpu_quota{pod=~\"$Pod\",container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\"}/100000) by (container, pod)) * 100"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod=~\"$Pod\",container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\"}[2m])) by (container, pod)",
     "legendFormat": "CPU核数使用"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",pod=~\"$Pod\",container=~\"$Container\",namespace=~\"$Namespace\"}) by (container,pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\",pod=~\"$Pod\",container=~\"$Container\",namespace=~\"$Namespace\"}) by (container,pod)"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"$Pod\",container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\"}) by (container, pod)/ sum(container_spec_memory_limit_bytes{pod=~\"$Pod\",container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\"}) by (container, pod) * 100",
     "legendFormat": "wss%"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"$Pod\",container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\"}) by (container, pod)",
     "legendFormat": "wss"
    },
    {
     "expr": "sum (container_memory_rss{pod=~\"$Pod\",container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\"}) by (container, pod)/ sum(container_spec_memory_limit_bytes{pod=~\"$Pod\",container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\"}) by (container, pod) * 100",
     "legendFormat": "rss%"
    },
    {
     "expr": "sum (container_memory_rss{pod=~\"$Pod\",container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\"}) by (container, pod)",
     "legendFormat": "rss"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\",pod=~\"$Pod\",container=~\"$Container\",namespace=~\"$Namespace\"}) by (container,pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\",pod=~\"$Pod\",container=~\"$Container\",namespace=~\"$Namespace\"}) by (container,pod)"
    },
    {
     "expr": "sum(container_fs_usage_bytes{pod=~\"$Pod\",container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\"}) by (container,pod)"
    },
    {
     "expr": "kube_pod_container_status_restarts_total{pod=~\"$Pod\",container=~\"$Container\",namespace=~\"$Namespace\"} - 0"
    },
    {
     "expr": "cass_jvm_heap{service=~\"$Container\"} * on (pod_ip) group_right(service) kube_pod_info{pod=~\"$Pod\",namespace=~\"$Namespace\"}"
    },
    {
     "expr": "cass_jvm_heap_max{service=~\"$Container\"} * on (pod_ip) group_right(service) kube_pod_info{pod=~\"$Pod\",namespace=~\"$Namespace\"}"
    },
    {
     "expr": "cass_jvm_noheap{service=~\"$Container\"} * on (pod_ip) group_right(service) kube_pod_info{pod=~\"$Pod\",namespace=~\"$Namespace\"}"
    },
    {
     "expr": "cass_jvm_noheap_max{service=~\"$Container\"} * on (pod_ip) group_right(service) kube_pod_info{pod=~\"$Pod\",namespace=~\"$Namespace\"}"
    }
   ]
  },
  {
   "title": "Container Application and Pod Resource Curve",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 }
  },
  {
   "title": "容器应用整体CPU使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=~\"$Container\",container!=\"\",container!=\"POD\",namespace=~\"$Namespace\"}[2m])) by (container) / (sum(container_spec_cpu_quota{container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\"}/100000) by (container)) * 100",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "容器应用整体内存使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 49 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container=~\"$Container\",container!=\"\",container!=\"POD\",namespace=~\"$Namespace\"}) by (container)/ sum(container_spec_memory_limit_bytes{container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\"}) by (container) * 100",
     "legendFormat": "WSS：{{ container }}"
    },
    {
     "expr": "sum (container_memory_rss{container=~\"$Container\",container!=\"\",container!=\"POD\",namespace=~\"$Namespace\"}) by (container)/ sum(container_spec_memory_limit_bytes{container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\"}) by (container) * 100",
     "legendFormat": "RSS：{{ container }}"
    }
   ]
  },
  {
   "title": "容器应用整体内存使用量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\"}) by (container)",
     "legendFormat": "WSS：{{ container }}"
    },
    {
     "expr": "sum (container_memory_rss{container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\"}) by (container)",
     "legendFormat": "RSS：{{ container }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\",container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\"}) by (container)",
     "legendFormat": "limits：{{ container }}"
    }
   ]
  },
  {
   "title": "Pod容器CPU使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod=~\"$Pod\",container=~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$Namespace\"}[2m])) by (container, pod) / (sum(container_spec_cpu_quota{pod=~\"$Pod\",container=~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$Namespace\"}/100000) by (container, pod)) * 100",
     "legendFormat": "{{ pod }}：{{  container  }}"
    }
   ]
  },
  {
   "title": "Pod容器内存使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"$Pod\",container=~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$Namespace\"}) by (container, pod)/ sum(container_spec_memory_limit_bytes{pod=~\"$Pod\",container=~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$Namespace\"}) by (container, pod) * 100",
     "legendFormat": "WSS：{{ pod }}：{{container}}"
    },
    {
     "expr": "sum (container_memory_rss{pod=~\"$Pod\",container=~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$Namespace\"}) by (container, pod)/ sum(container_spec_memory_limit_bytes{pod=~\"$Pod\",container=~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$Namespace\"}) by (container, pod) * 100",
     "legendFormat": "RSS：{{ pod }}：{{container}}"
    },
    {
     "expr": "(cass_jvm_heap{service=~\"$Container\"} * on (pod_ip) group_right(service) kube_pod_info{pod=~\"$Pod\",namespace=~\"$Namespace\"}) / (cass_jvm_heap_max{service=~\"$Container\"} * on (pod_ip) group_right(service) kube_pod_info{pod=~\"$Pod\",namespace=~\"$Namespace\"}) * 100",
     "legendFormat": "Heap：{{ pod }}：{{container}}"
    }
   ]
  },
  {
   "title": "Pod容器内存使用量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"$Pod\",container=~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$Namespace\"}) by (container, pod)",
     "legendFormat": "WSS：{{ pod }}：{{container}}"
    },
    {
     "expr": "sum (container_memory_rss{pod=~\"$Pod\",container=~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$Namespace\"}) by (container, pod)",
     "legendFormat": "RSS：{{ pod }}：{{container}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\",pod=~\"$Pod\",container=~\"$Container\",namespace=~\"$Namespace\"}) by (container,pod)",
     "legendFormat": "limits：{{ pod }}：{{container}}"
    },
    {
     "expr": "cass_jvm_heap{service=~\"$Container\"} * on (pod_ip) group_right(service) kube_pod_info{pod=~\"$Pod\",namespace=~\"$Namespace\"}",
     "legendFormat": "Heap：{{ pod }}：{{container}}"
    }
   ]
  }
 ]
}