{
 "title": "Kubernetes Resource Requests",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU Cores",
   "type": "graph",
   "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    {
     "expr": "min(sum(kube_node_status_allocatable_cpu_cores) by (instance, namespace)) by (namespace)",
     "legendFormat": "allocatable namespace: {{namespace}}"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_requests_cpu_cores) by (instance, namespace)) by (namespace)",
     "legendFormat": "requested namespace: {{namespace}}"
    }
   ]
  },
  {
   "title": "Requested / Limited CPU Cores",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_resource_requests_cpu_cores) by (instance, namespace)) by (namespace) / min(sum(kube_pod_container_resource_limits_cpu_cores) by (instance, namespace)) by (namespace) * 100",
     "legendFormat": "namespace: {{namespace}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "This represents the total [memory resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory) in the cluster.\nFor comparison the total [allocatable memory](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "min(sum(kube_node_status_allocatable_memory_bytes) by (instance, namespace)) by (namespace)",
     "legendFormat": "allocatable namespace: {{namespace}}"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_requests_memory_bytes) by (instance, namespace))  by (namespace)",
     "legendFormat": "requested namespaces: {{namespace}}"
    }
   ]
  },
  {
   "title": "Requested/Limited Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_resource_requests_memory_bytes) by (instance, namespace)) by (namespace) / min(sum(kube_pod_container_resource_limits_memory_bytes) by (instance, namespace)) by (namespace) * 100",
     "legendFormat": "namespace: {{namespace}}"
    }
   ]
  }
 ]
}