{
 "title": "Rancher Global Monitoring",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster or Node CPU / Memory / Disk usage as well as individual pods, containers, systemd services statistics.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "top10filter", "label": "View", "query": ",.*|" },
   {
    "name": "top_cpu_cluster_id",
    "query": "query_result(topk(10, max_over_time((1 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (prometheus_from)))[${__range_s}s:])))"
   },
   {
    "name": "top_memory_cluster_id",
    "query": "query_result(topk(10, max_over_time((1 - sum(node_memory_MemAvailable_bytes) by (prometheus_from) / sum(node_memory_MemTotal_bytes) by (prometheus_from))[${__range_s}s:])))"
   },
   {
    "name": "top_fs_size_cluster_id",
    "query": "query_result(topk(10, max_over_time(((sum(node_filesystem_size_bytes{device!~\"rootfs|HarddiskVolume.+\"}) by (prometheus_from) - sum(node_filesystem_free_bytes{device!~\"rootfs|HarddiskVolume.+\"}) by (prometheus_from)) / sum(node_filesystem_size_bytes{device!~\"rootfs|HarddiskVolume.+\"}) by (prometheus_from))[${__range_s}s:])))"
   },
   {
    "name": "top_etcd_size_instance_id",
    "query": "query_result(topk(10, max_over_time(etcd_debugging_mvcc_db_total_size_in_bytes[${__range_s}s:])))"
   },
   {
    "name": "top_etcd_change_cluster_id",
    "query": "query_result(topk(10, max_over_time((floor(max(increase(etcd_server_leader_changes_seen_total[${__range_s}s])) by (prometheus_from)))[${__range_s}s:])))"
   },
   {
    "name": "top_apiserver_latency_instance_id",
    "query": "query_result(topk(10, max_over_time((sum(apiserver_request_duration_seconds_sum{verb!=\"WATCH\"}) by (instance,prometheus_from)/ sum(apiserver_request_duration_seconds_count{verb!=\"WATCH\"}) by (instance,prometheus_from))[${__range_s}s:])))"
   },
   {
    "name": "top_network_receive_node_id",
    "query": "query_result(topk(10, max_over_time( sum(rate(node_network_receive_bytes_total[5m])) by (prometheus_from, node, node_id)[${__range_s}s:])))"
   },
   {
    "name": "top_network_transmit_node_id",
    "query": "query_result(topk(10, max_over_time( sum(rate(node_network_transmit_bytes_total[5m])) by (prometheus_from, node, node_id)[${__range_s}s:])))"
   },
   {
    "name": "top_disk_read_node_id",
    "query": "query_result(topk(10, max_over_time( sum(rate(node_disk_read_bytes_total[5m])) by (prometheus_from, node, node_id)[${__range_s}s:])))"
   },
   {
    "name": "top_disk_written_node_id",
    "query": "query_result(topk(10, max_over_time( sum(rate(node_disk_written_bytes_total[5m])) by (prometheus_from, node, node_id)[${__range_s}s:])))"
   },
   {
    "name": "top_unhealthy_pod_cluster_id",
    "query": "query_result(topk(10, max_over_time((sum(kube_pod_status_ready{condition=\"false\"}) by (prometheus_from) - sum(kube_pod_status_phase{phase=\"Succeeded\"}) by (prometheus_from) + sum(kube_pod_status_scheduled{condition=\"false\"}) by (prometheus_from))[${__range_s}s:])))"
   },
   {
    "name": "top_unschedulable_pod_cluster_id",
    "query": "query_result(topk(10, max_over_time((sum(kube_pod_status_unschedulable) by (prometheus_from))[${__range_s}s:])))"
   },
   {
    "name": "top_pod_restart_cluster_id",
    "query": "query_result(topk(10, floor(sum(increase(kube_pod_container_status_restarts_total[${__range_s}s])) by (prometheus_from))))"
   },
   {
    "name": "top_cpu_request_container_id",
    "query": "query_result(topk(10, max_over_time(kube_pod_container_resource_requests_cpu_cores[${__range_s}s])))"
   },
   {
    "name": "top_memory_request_container_id",
    "query": "query_result(topk(10, max_over_time(kube_pod_container_resource_requests_memory_bytes[${__range_s}s])))"
   },
   {
    "name": "top_cpu_pod_id",
    "query": "query_result(topk(10, max_over_time(rate(container_cpu_usage_seconds_total{container=\"\", pod!=\"\"}[5m])[${__range_s}s:])))"
   },
   {
    "name": "top_memory_pod_id",
    "query": "query_result(topk(10, max_over_time(container_memory_working_set_bytes{container=\"\", pod!=\"\"}[${__range_s}s])))"
   },
   {
    "name": "top_network_receive_pod_id",
    "query": "query_result(topk(10, max_over_time(sum(rate(container_network_receive_bytes_total{pod!=\"\"}[5m])) by (pod_id)[${__range_s}s:])))"
   },
   {
    "name": "top_network_transmit_pod_id",
    "query": "query_result(topk(10, max_over_time(sum(rate(container_network_transmit_bytes_total{pod!=\"\"}[5m])) by (pod_id)[${__range_s}s:])))"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Clusters",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by (prometheus_from) (up))"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(kube_node_info)" }
   ]
  },
  {
   "title": "Pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(kube_pod_info)" }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (avg(irate(node_cpu_seconds_total{mode=\"idle\", prometheus_from=~\"$top10filter$top_cpu_cluster_id\"}[5m])) by (prometheus_from))",
     "legendFormat": "{{prometheus_from}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - sum(node_memory_MemAvailable_bytes{prometheus_from=~\"$top10filter$top_memory_cluster_id\"}) by (prometheus_from) / sum(node_memory_MemTotal_bytes{prometheus_from=~\"$top_memory_cluster_id\"}) by (prometheus_from)",
     "legendFormat": "{{prometheus_from}}"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{device!~\"rootfs|HarddiskVolume.+\", prometheus_from=~\"$top10filter$top_fs_size_cluster_id\"}) by (prometheus_from) - sum(node_filesystem_free_bytes{device!~\"rootfs|HarddiskVolume.+\", prometheus_from=~\"$top10filter$top_fs_size_cluster_id\"}) by (prometheus_from)) / sum(node_filesystem_size_bytes{device!~\"rootfs|HarddiskVolume.+\", prometheus_from=~\"$top10filter$top_fs_size_cluster_id\"}) by (prometheus_from)",
     "legendFormat": "{{prometheus_from}}"
    }
   ]
  },
  { "title": "Cluster Components", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "ETCD DB Size(MB)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_debugging_mvcc_db_total_size_in_bytes{instance=~\"$top10filter$top_etcd_size_instance_id\"} / 1024/1024",
     "legendFormat": "{{prometheus_from}}/{{node}}"
    }
   ]
  },
  {
   "title": "ETCD Leader Election",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(floor(max(increase(etcd_server_leader_changes_seen_total{prometheus_from=~\"$top10filter$top_etcd_change_cluster_id\"}[${__range_s}s])) by (prometheus_from)))",
     "legendFormat": "{{prometheus_from}}"
    }
   ]
  },
  {
   "title": "API Server Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apiserver_request_duration_seconds_sum{verb!=\"WATCH\",instance=~\"$top10filter$top_apiserver_latency_instance_id\"}) by (instance,prometheus_from)/ sum(apiserver_request_duration_seconds_count{verb!=\"WATCH\",instance=~\"$top10filter$top_apiserver_latency_instance_id\"}) by (instance,prometheus_from) * 1000",
     "legendFormat": "{{prometheus_from}}/{{instance}}"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Node Network Receive Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{node_id=~\"$top10filter$top_network_receive_node_id\"}[5m])) by (prometheus_from, node)",
     "legendFormat": "{{prometheus_from}}/{{node}}"
    }
   ]
  },
  {
   "title": "Node Network Transmit Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{node_id=~\"$top10filter$top_network_transmit_node_id\"}[5m])) by (prometheus_from, node)",
     "legendFormat": "{{prometheus_from}}/{{node}}"
    }
   ]
  },
  {
   "title": "Node Disk Read Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{node_id=~\"$top10filter$top_disk_read_node_id\"}[5m])) by (node)",
     "legendFormat": "{{prometheus_from}}/{{node}}"
    }
   ]
  },
  {
   "title": "Node Disk Write Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_written_bytes_total{node_id=~\"$top10filter$top_disk_written_node_id\"}[5m])) by (prometheus_from, node)",
     "legendFormat": "{{prometheus_from}}/{{node}}"
    }
   ]
  },
  { "title": "Workload Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Unhealthy Pod Number",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{condition=\"false\", prometheus_from=~\"$top10filter$top_unhealthy_pod_cluster_id\"}) by (prometheus_from) - sum(kube_pod_status_phase{phase=\"Succeeded\", prometheus_from=~\"$top10filter$top_unhealthy_pod_cluster_id\"}) by (prometheus_from) + sum(kube_pod_status_scheduled{condition=\"false\", prometheus_from=~\"$top10filter$top_unhealthy_pod_cluster_id\"}) by (prometheus_from)",
     "legendFormat": "{{prometheus_from}}"
    }
   ]
  },
  {
   "title": "Unschedulable Pod Number",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_scheduled{condition=\"false\", prometheus_from=~\"$top10filter$top_unschedulable_pod_cluster_id\"}) by (prometheus_from)",
     "legendFormat": "{{prometheus_from}}"
    }
   ]
  },
  {
   "title": "Pod Restart Times",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "floor(sum(increase(kube_pod_container_status_restarts_total{prometheus_from=~\"$top10filter$top_pod_restart_cluster_id\"}[5m])) by (prometheus_from))",
     "legendFormat": "{{prometheus_from}}"
    }
   ]
  },
  {
   "title": "Container CPU Reservation (milicore)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{id=~\"$top10filter$top_cpu_request_container_id\"} * 1000",
     "legendFormat": "{{prometheus_from}}/{{namespace}}/{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Container Memory Reservation (MB)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{id=~\"$top10filter$top_memory_request_container_id\"} / 1024 / 1024",
     "legendFormat": "{{prometheus_from}}/{{namespace}}/{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Pod CPU Usage(milicore)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"\", pod!=\"\", pod_id=~\"$top10filter$top_cpu_pod_id\"}[5m]) * 1000",
     "legendFormat": "{{prometheus_from}}/{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Memory Usage (MB)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container=\"\", pod_id=~\"$top10filter$top_memory_pod_id\", pod!=\"\"} / 1024 / 1024",
     "legendFormat": "{{prometheus_from}}/{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Network Receive Rate (KB/s)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod!=\"\", pod_id=~\"$top10filter$top_network_receive_pod_id\"}[5m])) by (prometheus_from, namespace, pod) / 1024",
     "legendFormat": "{{prometheus_from}}/{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Network Transmit Rate (KB/s)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod!=\"\", pod_id=~\"$top10filter$top_network_transmit_pod_id\"}[5m])) by (prometheus_from, namespace, pod) / 1024",
     "legendFormat": "{{prometheus_from}}/{{namespace}}/{{pod}}"
    }
   ]
  }
 ]
}