{
 "title": "Rancher Controllers",
 "tags": [ "rancher" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": {
     "query": "label_values(kubernetes_io_hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of clusters per Rancher instance",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(cluster_manager_cluster_owner) by (owner)"
    }
   ]
  },
  {
   "title": "Rancher server <-> Cluster ownership",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\n  cluster_manager_cluster_owner,\n\"_0_owner\", \"$1\", \"owner\", \"(.*)\"),\n\"_1_cluster\", \"$1\", \"cluster\", \"(.*)\") > 0"
    }
   ]
  },
  {
   "title": "Controller/Handler Execution Frequency in 2min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(lasso_controller_total_handler_execution[2m])",
     "legendFormat": "{{ name }}.{{handlerName}}"
    }
   ]
  },
  {
   "title": "Controller Execution Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(lasso_controller_total_handler_execution) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Controller/Handler Execution Total(TOP20)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20,lasso_controller_total_handler_execution)",
     "legendFormat": "{{ name }}.{{handlerName}}"
    }
   ]
  }
 ]
}