apiVersion: v1
data:
  password: {{ .Values.bigip.password | toString | b64enc | quote }}
  username: {{ .Values.bigip.username | toString | b64enc | quote }}
kind: Secret
metadata:
  name: bigip-login
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
type: Opaque
